package com.avg.security.Enum;

public enum AuthenCode {
    OK,
    EMAIL_ALREADY_REGISTERED,
    ACCOUNT_NOT_ACTIVATED,
    ACCOUNT_OR_PASSWORD_INCORRECT,
    ACCOUNT_LOCKED,
    ACCOUNT_EXPIRED,
    ACCOUNT_DISABLED,
    INVALID_TOKEN,
}
