server:
  port: 9001

spring:
  application:
    name: security
  datasource:
    username: 'root'
    url: jdbc:mysql://localhost:3306/user?createDatabaseIfNotExist=true
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: 'true'
      hibernate:
        ddl-auto: update
        show-sql: 'true'